backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: assets

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/faq/index.md"
        label: "FAQ Page"
        name: "faq"
        fields:
          - { name: template, label: Template Key, widget: hidden, default: "blog-post"}
          - { name: body, label: Body, widget: markdown }
      - file: "src/pages/testimonials/index.md"
        label: "Testimonials Page"
        name: "testimonials"
        fields:
          - { name: template, label: Template Key, widget: hidden, default: "blog-post"}
          - { name: body, label: Body, widget: markdown }
